<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Authors>zHaytam</Authors>
    <Description>Fork of existing https://github.com/Blazor-Diagrams/Blazor.Diagrams Library, used for NodeDev</Description>
    <AssemblyVersion>99.0.2</AssemblyVersion>
    <FileVersion>99.0.2</FileVersion>
    <RepositoryUrl>https://github.com/snakex64/Blazor.Diagrams</RepositoryUrl>
    <Version>99.0.2</Version>
    <PackageId>snakex64.Z.Blazor.Diagrams.Core</PackageId>
    <PackageTags>blazor diagrams diagramming svg drag</PackageTags>
    <Product>snakex64.Z.Blazor.Diagrams.Core</Product>
    <PackageIcon>ZBD.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\ZBD.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SvgPathProperties" />
  </ItemGroup>

</Project>
