<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Authors>snakex64</Authors>
    <Description>Fork of existing https://github.com/Blazor-Diagrams/Blazor.Diagrams Library, used for NodeDev</Description>
    <AssemblyVersion>99.0.2</AssemblyVersion>
    <FileVersion>99.0.2</FileVersion>
    <RepositoryUrl>https://github.com/snakex64/Blazor.Diagrams</RepositoryUrl>
    <Version>99.0.2</Version>
    <PackageId>snakex64.Z.Blazor.Diagrams.Algorithms</PackageId>
    <PackageTags>blazor diagrams diagramming svg drag algorithms layouts</PackageTags>
    <Product>snakex64.Z.Blazor.Diagrams.Algorithms</Product>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Blazor.Diagrams.Core\Blazor.Diagrams.Core.csproj" />
  </ItemGroup>

</Project>
